version: "3.3"
services:

  traefik:
    image: "traefik:v2.0"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.le.acme.email=trick@vanstaveren.us"
      - "--certificatesResolvers.le.acme.storage=/acme.json"
        #      - "--certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      # used during the challenge
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:7082"
        #- "--metrics.prometheus.manualrouting=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metrics.rule=Host(`home.v9n.us`) && Path(`/metrics`)"
      - "traefik.http.routers.metrics.entrypoints=websecure"
      - "traefik.http.routers.metrics.tls.certresolver=le"
      - "traefik.http.services.metrics.loadbalancer.server.port=7082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json:rw"
    network_mode: host

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=America/Chicago
    restart: always
    network_mode: host
    labels:
      - "traefik.enable=true"
        #- "traefik.http.routers.hass.rule=Host(`home.v9n.us`) || Host(`hass.vanstaveren.us`)"
      - "traefik.http.routers.hass.rule=Host(`hass.vanstaveren.us`)"
      - "traefik.http.routers.hass.entrypoints=websecure"
      - "traefik.http.routers.hass.tls.certresolver=le"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"
